//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenci_akademisyen.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class akademisyenler
    {
        public int akademisyen_id { get; set; }
        public string akademisyen_ad { get; set; }
        public string akademisyen_soyad { get; set; }
        public Nullable<bool> akademisyen_cinsiyet { get; set; }
        public string akademisyen_unvan { get; set; }
        public string akademisyen_numara { get; set; }
        public string akademisyen_sifre { get; set; }
        public string akademisyen_mail { get; set; }
    }
}
