//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenci_akademisyen.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ogrencisinavEntities : DbContext
    {
        public ogrencisinavEntities()
            : base("name=ogrencisinavEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<akademisyenler> akademisyenler { get; set; }
        public virtual DbSet<bolumler> bolumler { get; set; }
        public virtual DbSet<dersler> dersler { get; set; }
        public virtual DbSet<notlar> notlar { get; set; }
        public virtual DbSet<ogrenciler> ogrenciler { get; set; }
        public virtual DbSet<notlistele> notlistele { get; set; }
    }
}
