//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenci_akademisyen.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class notlistele
    {
        public int id { get; set; }
        public string ogr_ad { get; set; }
        public string ogr_soyad { get; set; }
        public Nullable<byte> sinav1 { get; set; }
        public Nullable<byte> sinav2 { get; set; }
        public Nullable<byte> sinav3 { get; set; }
        public Nullable<byte> quiz1 { get; set; }
        public Nullable<byte> quiz2 { get; set; }
        public Nullable<byte> proje { get; set; }
        public Nullable<decimal> ortalama { get; set; }
        public Nullable<int> ders { get; set; }
        public string ders_ad { get; set; }
    }
}
