//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenci_akademisyen.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenciler()
        {
            this.notlar = new HashSet<notlar>();
        }
    
        public int ogr_id { get; set; }
        public string ogr_ad { get; set; }
        public string ogr_soyad { get; set; }
        public Nullable<bool> ogr_cinsiyet { get; set; }
        public string ogr_numara { get; set; }
        public string ogr_sifre { get; set; }
        public string ogr_mail { get; set; }
        public string ogr_resim { get; set; }
        public Nullable<int> bolum { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual bolumler bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notlar> notlar { get; set; }
    }
}
