//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bastan.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ogrencisinavEntities : DbContext
    {
        public ogrencisinavEntities()
            : base("name=ogrencisinavEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<akademisyenler> akademisyenler { get; set; }
        public virtual DbSet<bolumler> bolumler { get; set; }
        public virtual DbSet<dersler> dersler { get; set; }
        public virtual DbSet<ogrenciler> ogrenciler { get; set; }
        public virtual DbSet<notlar> notlar { get; set; }
        public virtual DbSet<notlistele> notlistele { get; set; }
    
        public virtual ObjectResult<notgetir_Result> notgetir(Nullable<int> dersid)
        {
            var dersidParameter = dersid.HasValue ?
                new ObjectParameter("dersid", dersid) :
                new ObjectParameter("dersid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir_Result>("notgetir", dersidParameter);
        }
    
        public virtual ObjectResult<notgetir2_Result> notgetir2(Nullable<int> dersid)
        {
            var dersidParameter = dersid.HasValue ?
                new ObjectParameter("dersid", dersid) :
                new ObjectParameter("dersid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir2_Result>("notgetir2", dersidParameter);
        }
    
        public virtual ObjectResult<notgetir3_Result> notgetir3(Nullable<int> ogrid)
        {
            var ogridParameter = ogrid.HasValue ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir3_Result>("notgetir3", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir31_Result> notgetir31(Nullable<int> ogrid)
        {
            var ogridParameter = ogrid.HasValue ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir31_Result>("notgetir31", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir32_Result> notgetir32(string ogrid)
        {
            var ogridParameter = ogrid != null ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir32_Result>("notgetir32", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir4_Result> notgetir4(string ogrid)
        {
            var ogridParameter = ogrid != null ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir4_Result>("notgetir4", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir5_Result> notgetir5(string ogrid)
        {
            var ogridParameter = ogrid != null ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir5_Result>("notgetir5", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir6_Result> notgetir6(string ogrid)
        {
            var ogridParameter = ogrid != null ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir6_Result>("notgetir6", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir7_Result> notgetir7(string ogrid)
        {
            var ogridParameter = ogrid != null ?
                new ObjectParameter("ogrid", ogrid) :
                new ObjectParameter("ogrid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir7_Result>("notgetir7", ogridParameter);
        }
    
        public virtual ObjectResult<notgetir8_Result> notgetir8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir8_Result>("notgetir8");
        }
    
        public virtual ObjectResult<notgetir9_Result> notgetir9(Nullable<int> dersid)
        {
            var dersidParameter = dersid.HasValue ?
                new ObjectParameter("dersid", dersid) :
                new ObjectParameter("dersid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notgetir9_Result>("notgetir9", dersidParameter);
        }
    }
}
