//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bastan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class notlar
    {
        public int id { get; set; }
        public Nullable<int> sinav1 { get; set; }
        public Nullable<int> sinav2 { get; set; }
        public Nullable<int> sinav3 { get; set; }
        public Nullable<int> quiz1 { get; set; }
        public Nullable<int> quiz2 { get; set; }
        public Nullable<int> proje { get; set; }
        public Nullable<decimal> ortalama { get; set; }
        public Nullable<int> ders { get; set; }
        public Nullable<int> ogrenci { get; set; }
    
        public virtual dersler dersler { get; set; }
        public virtual ogrenciler ogrenciler { get; set; }
    }
}
