//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uruntakib_entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alisverisEntities : DbContext
    {
        public alisverisEntities()
            : base("name=alisverisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<satislar> satislar { get; set; }
        public virtual DbSet<urun_tur> urun_tur { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<markalar> markalar { get; set; }
        public virtual DbSet<sehirler> sehirler { get; set; }
    }
}
