//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uruntakib_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        public int id { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<decimal> toplam { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual musteri musteri1 { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
